bin/geninfo
bin/lcov

find xxx -name \*.gcda -type f -o type l
does return :
- all files with the .gcda suffix
- all symbolic links
the updated command line now returns
- all files with the .gcda suffix
- all symbolic links with the .gcda suffix
Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

Fix find command line

---

bin/geninfo

The tracefiles now include line, function and line summary entries
(LF, LH, FNF, FNH, BRF and BRH) when processing GCOV text or json
intermediate format.
This makes the diff test to pass again when using GCOV versions that
support text or json intermediate format.
Signed-off-by: Jesus Gonzalez <jgonzalez@gdr-sistemas.com>

Fixed processing GCOV intermediate format.

---

bin/genhtml

Currently, if you have source code that lives in the top-level of your
project but you have that top-level set as a prefix, genhtml will not do
anything to truncate the prefix for the directory link.
Assume genhtml is called with `--prefix /home/wak/project`
Example layout:
/home/wak/project/lib.cpp
/home/wak/project/test/test_lib.cpp
This would result in generating an index.html with Directories:
/home/wak/project
test
This is not expected. Looking at the convention for top level
directories, we should be calling these directories "root".
With the patch applied, the index.html has Directories:
root
test

genhtml: Fix applying prefix to a prefix filename

---

bin/geninfo
lcovrc
man/geninfo.1
man/lcovrc.5

Branch coverage of C++ files is too often too low because exceptions happen in generated code all over the place: when an object is created dynamically, when a function or method is called, etc.
For many projects the testing strategy consists in testing all explicit branches (branches that actually are present in source code), and testing implicit exception branches is out of scope, just because testing most exception branches is very complicated as most of them are related to out-of-memory exceptions and that would require an enormous effort that doesn't compensate the benefits.
If we don't care about exception branches, exploring coverage reports full of not interesting errors is tedious and the probabilities of overlooking a "real" lack of branch coverage are high. Having to manually …

Enabled collection of branch coverage data but excluding exception branches.

---

bin/lcov
man/lcov.1

This allows requiring a certain line coverage during CI.
This is modeled after python's "coverage report --fail-under=100" or
nodejs' "nyc report --statements 100", but it's for line coverage.
Signed-off-by: Miklos Vajna <vmiklos@collabora.com>

lcov: add a new --fail-under-lines option

---

bin/genhtml
bin/geninfo
bin/lcov
bin/spreadsheet.py
lcovrc
lib/lcovutil.pm
man/genhtml.1
man/geninfo.1
man/lcov.1
man/lcovrc.5
tests/gendiffcov/simple/script.sh
tests/lcov/extract/extract.cpp
tests/lcov/extract/extract.sh

improve CPU performance and to eliminate copy-paste/redundant code. Side effect is to make 'checksum' a generic feature of geninfo/lcov/genhtml.

Use binary intermediate form to improve geninfo performance

---

Makefile
bin/genhtml
bin/geninfo
bin/lcov
lcovrc
lib/lcovutil.pm
man/genhtml.1
man/geninfo.1
man/lcov.1
man/lcovrc.5

Handle negative hit/taken values - typically caused by gcc bug: see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68080
Add message type 'count', and add feature to suppress additional messages after threshold is excceeded.
If user is not going to fix the first N messages, then there is no point to reporting more.

Handle negative hit count:  report as ignorable error, set to zero.

---

man/genhtml.1

Updated genhtml docs to correctly show branch coverage is disabled by default.
Signed-off-by: Jake Leventhal [jakeleventhal@me.com](mailto:jakeleventhal@me.com)

Incorrect genhtml man description

---

bin/geninfo

Correction of a typo in the function name: ingnorable_warning -> ignorable_warning

bin/geninfo - fix: ingnorable_warning  -> ignorable_warning

---

bin/genhtml

In this portion of code, $line is referring to the line in the current code (i.e. $linemap->NEW). Therefore, when using $linemap->lookup, we should indicate this instead.

Fix bug in genhtml when identifying new code in functions

---

README

The readme installation instructions contain a command that does not work for some of the packages lcov depends on. For instance, trying to install `Scalar::Util` as per current suggested command (perl -MCPAN -e "install Scalar::Util") will result in:  Can't locate object method "install" via package "Scalar::Util" at -e line 1.
Additionally, the maintainers might want to offer a one-liner to install all the perl packages at once:
```bash
for package in Capture::Tiny DateTime Devel::Cover Digest::MD5 File::Spec \
JSON Memory::Process Module::Load::Conditional Scalar::Util Time::HiRes; \
do yes "yes" | perl -MCPAN -e "install(${package})"; done
```

Update README: installation instructions

---

bin/geninfo

The expression
```perl
grep($p, @lcovutil::internal_dirs)
```
always evaluates to
```perl
@lcovutil::internal_dirs
```
and so evaluates to `true` as soon as `@lcovutil::internal_dirs` has one or more elements.

Fix identification of internal directories

---

man/geninfo.1

This commit fixes a very small typo in `geninfo(1)`.
Noticed this while writing a parser for `.info` files. The documentation looks perfect otherwise so I figured this warranted the effort of a PR on my part.
`lcov` is an excellent tool, thank you for putting in the effort to maintain it.

Bugfix: typo in geninfo.1

---

bin/genhtml

For a function templated on `T` returning an `boost::optional<T>`, I am seeing many repeated incomplete function signatures on the "functions" page for a header file. On inspecting the HTML, each represents a unique specialization of the template, but because the angle brackets aren't escaped, template parameters are eaten by the HTML parser and each line looks the same, missing those template parameters.
The accompanying change appears to address this issue.

Escape function aliases, which may be templates

---

lib/lcovutil.pm

A previous change to `is_language` resulted in all files being assumed to be C code, which is fixed by this patch.

Fix language detection

---

bin/xml2lcovutil.py

Symptom was the following runtime output:
```
bin/xml2lcovutil.py:262: SyntaxWarning: invalid escape sequence '\s'
```

`xml2lcovutil.py`: Add missing raw string prefix

---

lib/lcovutil.pm

```console
bin/genhtml:        my $filename  = ReadCurrentSource::resolve_path($traceInfo->filename());
lib/lcovutil.pm:                        '"' . $traceInfo->filename() .
lib/lcovutil.pm:                            '"' . $traceInfo->filename() .
lib/lcovutil.pm:                    '"' . $traceInfo->filename() .
lib/lcovutil.pm:                           '"' . $traceInfo->filename() .
lib/lcovutil.pm:    $lcovutil::profileData{derive_end}{$traceInfo->filename()} = $end - $start;
lib/lcovutil.pm:                         '"' . $traceInfo->filename() .
lib/lcovutil.pm:                           '"' . $traceInfo->filename() .
lib/lcovutil.pm:        !TraceFile::is_language('perl', $traceInfo->filename());
lib/lcovutil.pm:                      '"' . $traceInfo->filename() .
lib/lcovutil.pm: …
```

`lib/lcovutil.pm`: Fix `->filename` access in `_deriveFunctionEndLines`

---

bin/py2lcov
bin/xml2lcovutil.py

`py2lcov` and `xml2lcov`: Fix command injection from `subprocess.run([..], shell=True, [..])` (fixes #350)

---

.github/workflows/run_test_suite.yml

In reaction to https://github.com/linux-test-project/lcov/issues/338#issuecomment-2552404402 …

Make GitHub Actions upload the test log as an artifact (related to #338)

---

.github/workflows/run_test_suite.yml
bin/py2lcov
bin/xml2lcov
bin/xml2lcovutil.py
tests/bin/test_run
tests/gendiffcov/errs/msgtest.sh
tests/lcov/errs/errs.sh
tests/py2lcov/py2lcov.sh

Python Coverage.py version differences, GitHub regression infrastructure.  See #343, #348

---

lib/lcovutil.pm
man/genhtml.1
tests/lcov/mcdc/main.cpp
tests/lcov/mcdc/mcdc.sh
tests/lcov/mcdc/test.cpp

identical to the corresponding branch:  reduce verbosity/noise.

Add '--filter mcdc' option - to remove MC/DC coverpoints which are

---

Makefile
bin/fix.pl

If user explicitly asks to use a particular verion (...by having it in her environment):  use it.

Do not remove '/usr/bin/env ...' paths in scripts.

---

tests/common.tst
tests/lcov/extract/extract.sh
tests/lcov/mcdc/mcdc.sh
tests/py2lcov/py2lcov.sh

default to git unless obviously p4

Testcase portability:  default to git unless obviously p4

---

tests/lcov/extract/extract.sh

```console
make: Entering directory '[..]/tests/lcov/extract'
Starting tests
lcov/extract/extract.sh ........... [fail] (time 4.7s, mem 58.8MB)
Skipping 228 previous lines (see [..]/tests//test.log)
...
functions...: 28.6% (2 of 7 functions)
branches....: 33.3% (8 of 24 branches)
Filter suppressions:
region:
2 instances
5 coverpoints
Message summary:
no messages were reported
Error:  did not find expected context field
EXITCODE ...: 1
1 tests executed, 0 passed, 1 failed, 0 skipped (time 4.7s, mem 58.8MB)
Result log stored in [..]/tests/test.log
make: *** [../../common.mak:116: check] Error 1
make: Leaving directory '[..]/tests/lcov/extract'
```
```console
make: Entering directory '[..]/tests/lcov/extract'
Starting tests
lcov/extract/extract.sh ........... [pass] (time 23.1s, mem 58.9MB) …
```

Make extraction tests work without `${USER}` (fixes #378)

---

.github/workflows/run_test_suite.yml

https://github.com/actions/runner-images/issues/11101

Get CI off of about-to-be-removed Ubuntu 20.04

---

Makefile

Less agressive 'uninstall' target:  don't remove directory unless it was created by 'install' process.

---

.github/workflows/run_test_suite.yml

@henry2cox I keep getting this mismatch error:
```
+ make check
Creating coverage files (2 tests, 5 source files)
Source tree ......... done (950 lines, 50 functions, 3428 branches)
Full coverage ....... done
Target coverage ..... done
Partial coverage .... done
Zero coverage ....... done
Starting tests
genhtml/full.sh ................... [pass] (time 0.5s, mem 47.0MB)
genhtml/zero.sh ................... [pass] (time 0.5s, mem 46.8MB)
genhtml/demangle.sh ............... [pass] (time 1.4s, mem 39.0MB)
genhtml/relative/relative.sh ...... [pass] (time 0.3s, mem 39.0MB)
genhtml/lambda/lambda.sh .......... [fail] (time 1.5s, mem 124.2MB)
Skipping 165 previous lines (see /home/runner/work/lcov-fork/lcov-fork/tests//test.log)
...
Lines executed:94.21% of 916
stderr: …
```

Start covering GCC 15 in CI

---

bin/genhtml

MC/DC layout bug fix.

---

man/lcov.1

Add missing man page entry for lcov option.

---

bin/genhtml
bin/geninfo
bin/lcov
man/geninfo.1
man/lcov.1

See '--large-files' entry in man geninfo(1), lcov(1).
This feature is equivalent to finding all the GCDA files which match the regexp(s), processing them serially, then finding the remining GCDA files and processing them in parallel - and then aggregating the result.
The feature just simplifies the Jenkins regression script.
More sophisticated scheduling is possible - but seems unnecessary at present.

Improved spaceout handling.

---

man/genhtml.1
man/lcov.1

DOCUMENTATION:  note that the .info file format is described in the 'geninfo' man page.

---

bin/genhtml
bin/geninfo
example/methods/iterate.c
tests/gendiffcov/insensitive/annotate.sh
tests/lcov/extract/extract.sh

Various fixes

---

bin/geninfo
tests/bin/test_run

BUGFIX:  there may be no GDCA file - e.g., in 'initial' capture.

---

bin/genhtml
man/genhtml.1

Clarify use of SOURCE_DATE_EPOCH environment variable. See #403.

---

bin/llvm2lcov
tests/llvm2lcov/llvm2lcov.sh
tests/llvm2lcov/main.cpp

This LLVM version introduces JSON data format '3.0.1', which adds 'fileId' to MC/DC entries. This enables using branches from expansions for transferring MC/DC coverage data from expansions to their call sites. It also helps to add correct expressions for some MC/DC branches belonging to groups that contain branches from expansions.

Add LLVM/21 support to llvm2lcov

---

lib/lcovutil.pm
man/genhtml.1

Doc clarification

---

lcovrc
lib/lcovutil.pm
man/genhtml.1
man/geninfo.1
man/lcov.1
man/lcovrc.5
tests/lcov/exception/exception.sh
tests/lcov/extract/extract.cpp
tests/lcov/extract/extract.sh
tests/lcov/mcdc/mcdc.sh

This is similar to 'excluded regions' - except that lcov will generate an 'unreachable' message if any coverpoints in the region are hit.

Add 'unreachable region' feature.
